main: main.o
	g++ -o main main.o

main.o: main.cpp
	g++ -c main.cpp

clean:
	rm -f main.o

help:
	@cat README.org

install:
	@echo This would install the system

uninstall:
	@echo and this would uninstall it
