one:
	@echo "Building target one"
	@echo "A second command to build target one"

help:
	@echo "This is a help message"

commands: dir pwd freespace

commands2: dir pwd freespace
	@echo "COMMAND DONE"

dir:
	@ls


pwd:
	@pwd

freespace:
	@df

